namespace AnalyticaDocs.Models
{
    public class MeterConsumptionViewModel
    {
        public int Srno { get; set; }
        public DateOnly? ReadDate { get; set; }
        public DateOnly? ShiftDate { get; set; }
        public int? MeterID100 { get; set; }
        public decimal? PrvRead100 { get; set; }
        public decimal? CurRead100 { get; set; }
        public decimal? MF100 { get; set; }
        public decimal? PF100 { get; set; }
        public decimal? Consumption100 { get; set; }
        public int? MeterID101 { get; set; }
        public decimal? PrvRead101 { get; set; }
        public decimal? CurRead101 { get; set; }
        public decimal? MF101 { get; set; }
        public decimal? PF101 { get; set; }
        public decimal? Consumption101 { get; set; }
        public int? MeterID102 { get; set; }
        public decimal? PrvRead102 { get; set; }
        public decimal? CurRead102 { get; set; }
        public decimal? MF102 { get; set; }
        public decimal? PF102 { get; set; }
        public decimal? Consumption102 { get; set; }
        public int? MeterID103 { get; set; }
        public decimal? PrvRead103 { get; set; }
        public decimal? CurRead103 { get; set; }
        public decimal? MF103 { get; set; }
        public decimal? PF103 { get; set; }
        public decimal? Consumption103 { get; set; }
        public int? MeterID104 { get; set; }
        public decimal? PrvRead104 { get; set; }
        public decimal? CurRead104 { get; set; }
        public decimal? MF104 { get; set; }
        public decimal? PF104 { get; set; }
        public decimal? Consumption104 { get; set; }
        public int? MeterID105 { get; set; }
        public decimal? PrvRead105 { get; set; }
        public decimal? CurRead105 { get; set; }
        public decimal? MF105 { get; set; }
        public decimal? PF105 { get; set; }
        public decimal? Consumption105 { get; set; }
        public int? MeterID106 { get; set; }
        public decimal? PrvRead106 { get; set; }
        public decimal? CurRead106 { get; set; }
        public decimal? MF106 { get; set; }
        public decimal? PF106 { get; set; }
        public decimal? Consumption106 { get; set; }
        public int? MeterID107 { get; set; }
        public decimal? PrvRead107 { get; set; }
        public decimal? CurRead107 { get; set; }
        public decimal? MF107 { get; set; }
        public decimal? PF107 { get; set; }
        public decimal? Consumption107 { get; set; }
        public int? MeterID108 { get; set; }
        public decimal? PrvRead108 { get; set; }
        public decimal? CurRead108 { get; set; }
        public decimal? MF108 { get; set; }
        public decimal? PF108 { get; set; }
        public decimal? Consumption108 { get; set; }
        public int? MeterID109 { get; set; }
        public decimal? PrvRead109 { get; set; }
        public decimal? CurRead109 { get; set; }
        public decimal? MF109 { get; set; }
        public decimal? PF109 { get; set; }
        public decimal? Consumption109 { get; set; }
        public int? MeterID110 { get; set; }
        public decimal? PrvRead110 { get; set; }
        public decimal? CurRead110 { get; set; }
        public decimal? MF110 { get; set; }
        public decimal? PF110 { get; set; }
        public decimal? Consumption110 { get; set; }
        public int? MeterID111 { get; set; }
        public decimal? PrvRead111 { get; set; }
        public decimal? CurRead111 { get; set; }
        public decimal? MF111 { get; set; }
        public decimal? PF111 { get; set; }
        public decimal? Consumption111 { get; set; }
        public int? MeterID112 { get; set; }
        public decimal? PrvRead112 { get; set; }
        public decimal? CurRead112 { get; set; }
        public decimal? MF112 { get; set; }
        public decimal? PF112 { get; set; }
        public decimal? Consumption112 { get; set; }
        public int? MeterID113 { get; set; }
        public decimal? PrvRead113 { get; set; }
        public decimal? CurRead113 { get; set; }
        public decimal? MF113 { get; set; }
        public decimal? PF113 { get; set; }
        public decimal? Consumption113 { get; set; }

    }
}
